### ISSUE TITLE
The providers stops querying for tiles 

### ISSUE THREAD

**Issue by mamayoleksandr** [kaktus40/Cesium-GeoserverTerrainProvider#11]
Am trying to use this provider with cesium 1.15. 
Initially it queries capabilities ok, and also some tiles are fetched ok (see attached), but then just stops and terrain on map not updated at all.

Here is how I use it:
```javascript
 var terrainProvider = new Cesium.GeoserverTerrainProvider({
                url : globals.geoserverUrl+"/elevation/wms",
                proxy : {
                    getURL: function(url){
                        return gisextGlobals.geoserverUrl+url.substr(url.indexOf('/elevation'));
                    }
                },
                layerName: "lidar_dem_full_rescaled"
            });
```
Any ideas what could it be?

thanks in advance.

![selection_068](https://cloud.githubusercontent.com/assets/930971/11806455/5815b95c-a324-11e5-8a0f-c49be2062aa3.png)

**Comment by mamayoleksandr** [comment]
Actually also getting this one:
WebGL: INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request with UNPACK_ALIGNMENT > 1

**Comment by kaktus40** [comment]
Hello, could you send me your capabilities document please

**Comment by Parthesh** [comment]
I too have the same problem i.e. I get the same WebGL warning in the console.. But in my case the terrain gets upgraded, but some black patches are appearing variably on the globe.

-- I have attached the capabilities documents (geoserver version 2.8.0, WMS version 1.1.1 and 1.3.0).
-- Also I have attached the snapshot of the issue.



![webgl_issue](https://cloud.githubusercontent.com/assets/8957598/11832115/13f44e34-a3db-11e5-95c8-488463854c0a.png)
[getcapabilities_1.1.1.txt](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/files/63548/getcapabilities_1.1.1.txt)
[getcapabilities_1.3.0.txt](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/files/63549/getcapabilities_1.3.0.txt)

**Comment by mamayoleksandr** [comment]
Here is the caps also
[ows.txt](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/files/63579/ows.txt)

**Comment by kaktus40** [comment]
Hello,
@mamayoleksandr , I don't see image/bil as a declared format in your capabilities document. You should first install bil/dds plugin. Maybe you translated your dem data with the java tool included in this repo? The geoserverterrainProvider try to parse from capabilities document which data to retrieve (first bil format and after png format). When it use png or jpeg format, it's suppose the images are translated unless there is a SLD style used.

@Parthesh and @mamayoleksandr I can't reproduct your issue with webGL:
Which version of Cesium do you use?

**Comment by kaktus40** [comment]
It seems the webGL issue comes with waterMask initiates at true

**Comment by Parthesh** [comment]
I am getting this problem on Cesium 1.6, 1.13 and 1.16 as well. And even if I put waterMask value as 'false' it is the same.

**Comment by Parthesh** [comment]
Got the solution... Just used older version of geoserver i.e. Geoserver 2.7.5. Anyway, thanks for the support. It seems 2.8.0 is not properly supporting GTP.

**Comment by kaktus40** [comment]
Ok I work with geoserver 2.7.2. 
I'll test the with geoserver 2.8.1

**Comment by kaktus40** [comment]
Hello,
I test with geoserver 2.8.1 and latest version of cesium and it seems ok. Is it the same for you?
