### ISSUE TITLE
cesium serrated display

### ISSUE THREAD

**Issue by ysnsln** [kaktus40/Cesium-GeoserverTerrainProvider#14]
Hi,

I am using geoserver and bil format settings application/bil16   -   Big Endian, 

my code is;

   var terrainProvider = new Cesium.GeoserverTerrainProvider({
                    url: "http://localhost:8080/geoserver/test/wms?", 
                    layerName: "test",
                    maxLevel: 10,
                    highest: 12000,
                    lowest: -500,
                    heightMapWidth: 64,
                    heightMapHeight: 64
                });

What is your opinion about this problem?

![tirtik](https://cloud.githubusercontent.com/assets/16666564/12264161/67d778c4-b93d-11e5-958f-7b72143e4d91.PNG)

**Comment by kaktus40** [comment]
Hello,
could you check https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/7
