### ISSUE TITLE
Getting sharp edges on terrain with WMTS service

### ISSUE THREAD

**Issue by Parthesh** [kaktus40/Cesium-GeoserverTerrainProvider#16]
Following is the code I used:

```
var terrainProvider = new Cesium.GeoserverTerrainProvider({
    service : "WMTS",
    url : "http://localhost:8080/geoserver/gwc/service/wmts",
    layerName: "elevation:srtm_global_90m_tiled"
}); 
viewer.terrainProvider = terrainProvider;
```

It seems that "WMS" service is working fine, but when I try to use "WMTS" service, I get sharp edges on terrain.

I have attached the snapshot and getCapabilities doc. 

[wmts-getcapabilities.txt](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/files/100558/wmts-getcapabilities.txt)

![wmts_issue](https://cloud.githubusercontent.com/assets/8957598/12507281/bf5136c8-c11a-11e5-9cd2-276a94a0e05c.png)

**Comment by kaktus40** [comment]
Hello,
I think I forget to indicate that the layer must be translated with the little java tool in this repository.
Could you translate your data with GeotiffTranslate.zip please and see if there is a change?

**Comment by Parthesh** [comment]
Thanks, it works. May be you can add it in README.md.
