### ISSUE TITLE
stepped elevation levels

### ISSUE THREAD

**Issue by ceiblef** [kaktus40/Cesium-GeoserverTerrainProvider#18]
What am I doing wrong when the elevation looks stepped like you see in the image. I have used a srtm (90 meters) with pyramids and the styled variant for elevation transformation...
![image](https://cloud.githubusercontent.com/assets/19821079/15924337/d85b10d8-2e31-11e6-8a2f-7edac07be3dc.png)

**Comment by kaktus40** [comment]
Hello,
unfortunately, with styled variant has this backward: there is no interpolation of elevation so your image is normal.
For me, the styled variant is a fallback in case bil/DDS doen't work for some tiles.

**Comment by ceiblef** [comment]
Many thanks for your support!
