### ISSUE TITLE
Terrain look like Stairs

### ISSUE THREAD

**Issue by ohadmanor** [kaktus40/Cesium-GeoserverTerrainProvider#19]
Hi,

I'm new at this,

I'm using geoserver with dds/bill plugin to send the tiles. The DEM resolution is 10m.

When I'm in large zoom everything looks great but when I zoom in the terrain start to look like stairs

What do you think is the problem?
![untitled](https://cloud.githubusercontent.com/assets/9347444/21986850/c819d8e0-dc09-11e6-8507-492c8a5601d5.png)

Thanks

**Comment by kaktus40** [comment]
Hello, it's normal. This problem is linked to how cesium display the heightMap terrain. This problem doesn't exist with quantized-mesh terrain.

**Comment by ohadmanor** [comment]
Is there any quantized-mesh solution without using the STK?

**Comment by kaktus40** [comment]
you should see [this](https://github.com/loicgasser/quantized-mesh-tile)

**Comment by ohadmanor** [comment]
thanks.
