### ISSUE TITLE
Can we use .tif tiles as terrain tiles?

### ISSUE THREAD

**Issue by mrgloom** [kaktus40/Cesium-GeoserverTerrainProvider#20]
For now I'm using [cesium-terrain-builder](https://github.com/geo-data/cesium-terrain-builder) for producing terrain tiles in .terrain format, but I wonder can Cesium work with float .tif tiles (maybe using Cesium-GeoserverTerrainProvider)?

**Comment by kaktus40** [comment]
You should understand that the starting point to use Cesium-GeoserverTerrainProvider is geoserver with bil/DDS capabilities. So You must insert your data into geoserver before working with this plugin.
I recommand you to make a pyramid of tiles with gdal before use of geoserver. 
If you are interested, you should check [this](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/9#issuecomment-119314192).

**Comment by mrgloom** [comment]
I'm not sure what BIL/DDS means, as I understand for now my cesium app use apache server for supply .terrain tiles.

**Comment by kaktus40** [comment]
Check [this](http://docs.geoserver.org/latest/en/user/community/dds/index.html)
