### ISSUE TITLE
BBOX is outside of WGS84 limits

### ISSUE THREAD

**Issue by IgorGrechka** [kaktus40/Cesium-GeoserverTerrainProvider#22]
Hi!

I am trying to load BIL data from geoserver, but **templateToURL(urlParam, x, y, level, provider)** function attaches wrong bbox values to URL (see screenshot bellow). What can be the reason?

![image](https://user-images.githubusercontent.com/1829604/28210843-3cf9deec-68a2-11e7-9593-da33465e04be.png)

P.s. Cesium version 1.33
P.p.s. Let me know if you need more details!

Thank you in advance!

**Comment by kaktus40** [comment]
Hello, could you send your WMS capabilities document?

**Comment by IgorGrechka** [comment]
Hello, thanks for the answer! 

I can't send full xml, but I made two screenshots:

Geoserver GetMap capabilities:
![capture_1](https://user-images.githubusercontent.com/1829604/28258818-ee495af2-6adb-11e7-9e91-565dd08ccd3b.PNG)

And description of layer, which I'm trying to load:
![capture_2](https://user-images.githubusercontent.com/1829604/28258819-ee4a6bc2-6adb-11e7-9125-f10bfcdc7f7c.PNG)

Is it enough? Or you need more info?

**Comment by kaktus40** [comment]
It seems that all is correct.
I'm sorry but I take vacation and I can't help you until 19/08/2017...

**Comment by IgorGrechka** [comment]
Ok, I will wait! 
If new observations will come, I will let you know!

Have a good vacation!

**Comment by IgorGrechka** [comment]
Hi! I hope you are back and your vacation was perfect! :)

I am still having an issue, described above. 

Here my source code:
```
// create viewer
viewer = new Cesium.Viewer("map", {
        animation: false,
        timeline: false,
        homeButton: false,
        baseLayerPicker: false,
        navigationHelpButton: false,
        geocoder: false,
        infoBox: false,
        sceneModePicker: false,
        fullscreenButton: false,
        imageryProvider: new Cesium.createOpenStreetMapImageryProvider({
            url: "https://a.tile.openstreetmap.org/"
        }),
        contextOptions: {
            webgl: { preserveDrawingBuffer: true }
        }
});

// create terrain provider
var geoserverTerrainProvider = new Cesium.GeoserverTerrainProvider({
    url: geoServerUrl,
    layerName: "sf:sfdem"
});

// attach terrain provider
viewer.scene.globe.terrainProvider = geoserverTerrainProvider;
```
Request looks like this (bbox looks strange):
![capture](https://user-images.githubusercontent.com/1829604/29653254-be3d514e-88b1-11e7-9972-c409e743679e.PNG)

And response is ServiceExceptionReport:
```
<ServiceException>
      Error rendering coverage on the fast path  java.lang.NullPointerException
</ServiceException>
```

Do you have any idea what can be the reason?

Thanks!

**Comment by kaktus40** [comment]
It's very strange, from what I understand, your layer sf:dem has the next bounding box in CRS:84:
 - south or minx : -103.871006...
 - west or miny: 44.3702...
 - north or maxx: -103.6293...
 - east or maxy: 44.5016...

For record, the bbox for CRS:84 in WMS request is define in this order: '{south},{west},{north},{east}' so the biggest rectangle that can be requested should be bbox=**-103.871006, 44.3702, -103.6293,44.5016** and you have a request with bbox= **-181,-91,1.40,91**

Could you add some line codes in the code of plugin? After line 368 (```retour = Cesium.defined(scratchRectangle);```), could you add the next lines and show me the result:
```

                            if(retour){
                                console.log('reference: west'+rectReference.west+'; south:'+rectReference.south+'; east:'+rectReference.east+'; north:'+rectReference.north);
                                console.log('calcul: west'+rectangleCalcul.west+'; south:'+rectangleCalcul.south+'; east:'+rectangleCalcul.east+'; north:'+rectangleCalcul.north);
                                console.log('result: west'+scratchRectangle.west+'; south:'+scratchRectangle.south+'; east:'+scratchRectangle.east+'; north:'+scratchRectangle.north);
                            }
```

**Comment by IgorGrechka** [comment]
I added this lines here:
![capture](https://user-images.githubusercontent.com/1829604/29807403-853eee40-8c9c-11e7-9d27-5c6ce9fcd662.PNG)

Result from console:
![capture1](https://user-images.githubusercontent.com/1829604/29807437-b3840e2a-8c9c-11e7-92cf-304b363abb62.PNG)

**Comment by IgorGrechka** [comment]
Sorry, I closed issue by mistake.

**Comment by IgorGrechka** [comment]
I also made one screenshot of **templateToURL(urlParam, x, y, level, provider)** values. Maybe it can be helpfull:
![capture2](https://user-images.githubusercontent.com/1829604/29808021-2745ba5a-8c9f-11e7-9e17-a96033329730.PNG)

**Comment by kaktus40** [comment]
Well from what I see, all work well as I defined. I should add a max limit to rectangle according to the tilingScheme. This limit should be adaptable also.

Envoyé par BlueMail<http://www.bluemail.me/r?b=10455>
Le 29 août 2017, à 08:48, IgorGrechka <notifications@github.com<mailto:notifications@github.com>> a écrit:

I also made one screenshot of templateToURL(urlParam, x, y, level, provider) values. Maybe it can be helpfull:
[capture2]<https://user-images.githubusercontent.com/1829604/29808021-2745ba5a-8c9f-11e7-9e17-a96033329730.PNG>

**Comment by kaktus40** [comment]
Hello which is the version of geoserver. It seems there some issues with old versions
Le 29 août 2017, à 08:48, IgorGrechka <notifications@github.com<mailto:notifications@github.com>> a écrit:

I also made one screenshot of templateToURL(urlParam, x, y, level, provider) values. Maybe it can be helpfull:
[capture2]<https://user-images.githubusercontent.com/1829604/29808021-2745ba5a-8c9f-11e7-9e17-a96033329730.PNG>

**Comment by IgorGrechka** [comment]
Hi! Please look at GeoServer's about page:
![capture](https://user-images.githubusercontent.com/1829604/29871551-d46115ae-8d94-11e7-9665-ae0ae45048c4.PNG)

**Comment by kaktus40** [comment]
Is it possible for you to update the version of geoserver?From what I saw on internet, may be one piece of your dataset is bad...
Le 30 août 2017, à 14:07, IgorGrechka <notifications@github.com<mailto:notifications@github.com>> a écrit:

Hi! Please look at GeoServer's about page:
[capture]<https://user-images.githubusercontent.com/1829604/29871551-d46115ae-8d94-11e7-9665-ae0ae45048c4.PNG>

**Comment by IgorGrechka** [comment]
Ok. I will check the possibility of updating the GeoServer to the latest stable version and let you know. 

P.s. Maybe you know, where I can get correct dataset for testing?

**Comment by kaktus40** [comment]
Well in the end of readme.md<http://readme.md> I give some links...

Envoyé par BlueMail<http://www.bluemail.me/r?b=10455>
Le 30 août 2017, à 15:36, IgorGrechka <notifications@github.com<mailto:notifications@github.com>> a écrit:

Ok. I will check the possibility of updating the GeoServer to the latest stable version and let you know.

P.s. Maybe you know, where I can get correct dataset for testing?

**Comment by IgorGrechka** [comment]
Hi!

I updated GeoServer to version 2.11.2

![gsv](https://user-images.githubusercontent.com/1829604/30030372-92ea7746-9195-11e7-9ece-1233fa24120c.PNG)

Now the globe is loading (the half of the globe)

![1](https://user-images.githubusercontent.com/1829604/30030403-b61b7eea-9195-11e7-97c5-f44ef44ed5cb.PNG)

BBOX in first request is outside limits:
![r1](https://user-images.githubusercontent.com/1829604/30030438-e9d31bbc-9195-11e7-8eea-417fc16021a9.PNG)
but after starting rotating\zooming the globe it becomes correct:
![r3](https://user-images.githubusercontent.com/1829604/30030449-fcf348ca-9195-11e7-9429-5f89f90292c2.PNG)

But previously it was only one request after "GetCapabilities" and globe wasn't load. So I can say that update of GeoServer have resolved the issue.

Bit terrain looks like bellow:

![2](https://user-images.githubusercontent.com/1829604/30030633-dada28a2-9196-11e7-92a7-df673d25544e.PNG)

Layer preview in GeoServer looks like this:

![gs](https://user-images.githubusercontent.com/1829604/30030644-e9610af8-9196-11e7-951f-c2b7fd9e92c6.PNG)

Can you tell me what is the reason of wrong terrain visualization and why Cesium loads exactly half of the globe?

Thank you!

**Comment by kaktus40** [comment]
hello,
for the  wrong terrain visualization, you should check https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/9#issuecomment-119314192 for example. By default the plugin works with data in Integer 16 bit format. Your data is on a float format (32 or 64 bit?). In this comment, you should find a solution.

For the half earth not rendered, it's also normal because cesium use function to determine if a tile is available. If a tile is not available, Cesium doesn't download the image corresponding.
A workaround (for WMS) is to change this [function](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/GeoserverTerrainProvider.js#L363-L371) so it always returns true!

**Comment by IgorGrechka** [comment]
Hi! I checked the original image format and you are wright, it is in Float32 format.
GDALinfo of image:
![gi_orig](https://user-images.githubusercontent.com/1829604/30052068-fbb1c332-922c-11e7-9ae1-98afccbf8d50.PNG)

After I tryed to convert it using
`gdalwarp -ot Int16 -co "TILED=YES" -co "COMPRESS=DEFLATE" -r cubicspline "C:\sfdem_orig.tif" "C:\sfdem_conv.tif"`

GDALinfo of converted image:
![gi_conv](https://user-images.githubusercontent.com/1829604/30052154-45e3a718-922d-11e7-8a87-b1fb83573c16.PNG)

But the result is same:
![result](https://user-images.githubusercontent.com/1829604/30052226-6c2f39be-922d-11e7-9d17-4fa32b64dbf3.PNG)

If it required, I can upload original and converted images somewhere!

**Comment by kaktus40** [comment]
It seems you have a problem with the endiannes of your data (easily corrected in bil/DDS parameters in geoserver).
You didn't have to convert your data in int 16 bit data. If you follow my [comment](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/9#issuecomment-119314192), you just need to check the parameter in geoserver and implement postProcessArray when you use the plugin!

**Comment by IgorGrechka** [comment]
Thanks a lot for your help!

I copied your  **formatArray** implementation and changed **Default Encoding** and **Byte Order** in GeoServer layer settings. Now the picture looks fine:
![capture](https://user-images.githubusercontent.com/1829604/30053839-cf1f8182-9232-11e7-93b0-24c0ea0f4657.PNG)

As I understand - this "stair" is the end of elevation map in GeoServer. Am I wright?

**Comment by kaktus40** [comment]
Yes that right!
