### ISSUE TITLE
Using UInt32 tiles

### ISSUE THREAD

**Issue by IgorGrechka** [kaktus40/Cesium-GeoserverTerrainProvider#23]
Hi and thanks again for your great work!

As I know by default the plugin works with data in Integer 16 bit format. Float32 also can be used with implementation of **formatArray** method, provided by you.

Is there any ability to use elevation map with data in UInt32 bit format without convertation with terrain provider?

GdalInfo:
![capture](https://user-images.githubusercontent.com/1829604/31265919-026cb97e-aa7a-11e7-8c1d-8dde5a5cdf4e.PNG)

Please let me know if you need more info or data sample!
Thanks in advance!

**Comment by kaktus40** [comment]
Hello,
you should use formatArray with the implementation I gave you with one change:
``` temp = viewerIn.getFloat32(i, false) - offset;```
becomes
``` temp = viewerIn.getUint32(i,false) - offset;```
You should check the implementation of dataview [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView)

**Comment by IgorGrechka** [comment]
Hi and thanks for your answer!

I tried to made this change but there is no result (globe is still flat). Please see screenshot bellow:

![untitled](https://user-images.githubusercontent.com/1829604/31328285-c7a947ca-acdc-11e7-856b-dcb4e0ab0583.png)

I made change 1. I also tried to change 2, 3 point but result the same.
Can you tell me where I made a mistake?

**Comment by kaktus40** [comment]
Did you configure bil/DDS plugin in geoserver?

**Comment by IgorGrechka** [comment]
Sorry, what do you mean "configure"? It works perfect with test data in Float32 format. Do I need to do some additional configuration for Uint32 data?

**Comment by kaktus40** [comment]
Well in my version of the bill/DDS plugin it seems you can  define bil 8, bil 16 or bil 32 format with the endianness.
I think that bil 32 must be float format because I could indicate int 32 format!

**Comment by IgorGrechka** [comment]
For this layer (with images in Uint32 format) I'm using following settings:

![capture](https://user-images.githubusercontent.com/1829604/31331724-32515ac2-acec-11e7-99be-0d1c684688f2.PNG)

Is it OK in my case?

**Comment by kaktus40** [comment]
I think that OK. Now can you see something with float32?

**Comment by IgorGrechka** [comment]
With images in **Float32** format - everything fine, but with images in **Uint32** format - globe is flat.

**Comment by kaktus40** [comment]
Sorry I can't help you on this case because it seems being a limitation from geoserver or bil dds plug in. Maybe, it doesn't take unint32 format. You should post a request in the community of geoserver.

**Comment by IgorGrechka** [comment]
Understood. Anyway thanks for your answers!
