### ISSUE TITLE
BIL/DDS Extension Issue and Sample Code

### ISSUE THREAD

**Issue by sgeosol** [kaktus40/Cesium-GeoserverTerrainProvider#24]
I have installed the bil/dds extension but when i select BIL from the layer preview page of geoserver, a file is downloaded with following message in it

> Cannot get WMS bil tiles bigger than 512x512, try WCS

Also when i run the example code provided in README it produces following error

> Cesium.js:535 Uncaught TypeError: Cannot read property 'getContext' of undefined
    at new N (Cesium.js:535)
    at new Ee (Cesium.js:552)
    at cesium6.html:19

Line no. 19 at which the above error occurs is

`var scene = new Cesium.Scene(canvas);`

Kindly guide me regarding these two issues

Regards

**Comment by kaktus40** [comment]
Hello, for the first point it seems normal.
For the second point, could you provide me your geoserver version and cesium version.
Also you should use the unminified version of cesium.

**Comment by sgeosol** [comment]
Thanks for the reply.
Does it mean bil can only be consumed by any compatible application and not downloaded through a browser ?
My geoserver version is 2.9.1. and using Cesium 1.38. I just downloaded cesium from the main download link and its zip file is around 53 MB size. How to tell if its an unminified version or not ?

P.S. I am running it in Wamp server and my Apache version is 2.4.23

Thanks

**Comment by kaktus40** [comment]
No it only means that the plugin is not fit to generate a big data file. For this point, you should make a request to geoserver, I can't help you on this.
In your zip, there is a Build directory. You should use CesiumUnminified directory inside instead of Cesium.

You should update your release of geoserver (2.9.1 was released 2016-07-18).

**Comment by sgeosol** [comment]
Hi
I am running the following code

```
  <script>
    var viewer = new Cesium.Viewer('cesiumContainer');
    var canvas = document.getElementById('cesiumContainer');
    var scene = new Cesium.Scene({
      canvas : canvas,
      contextOptions : {
        allowTextureFilterAnisotropic : false
      }
    });
    var primitives = scene.primitives;
    var globe = new Cesium.Globe(Cesium.Ellipsoid.WGS84);
    scene.globe=globe;

    var terrainProvider = new Cesium.GeoserverTerrainProvider({
        url : "http://localhost:8080/geoserver/Test/wms",
        layerName: "Test:hiresdem",
        waterMask:true
    });
    globe.terrainProvider = terrainProvider;
    var hand = new Cesium.ScreenSpaceEventHandler(canvas);
    
hand.setInputAction(
            function (movement) {
                if(movement.position != null) {
                    var cartesian = scene.camera.pickEllipsoid(movement.position, ellipsoid);
                    if (cartesian) {
                        var cartographic = ellipsoid.cartesianToCartographic(cartesian);
                        cartographic.height=globe.getHeight(cartographic);
                        console.log("lat= "+(cartographic.latitude*180/Math.PI)+"°; long="+(cartographic.longitude*180/Math.PI)+"°; altitude="+cartographic.height+" meters")
                    }
                }
            }, Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
  </script>
```

running it produces the following error

> Cesium.js:159461 Uncaught TypeError: canvas.getContext is not a function
>     at new Context (Cesium.js:159461)
>     at new Scene (Cesium.js:205696)
>     at cesium5.html:28

Line no. 28 at which the above error occurs is

```
    var scene = new Cesium.Scene({
      canvas : canvas,
      contextOptions : {
        allowTextureFilterAnisotropic : false
      }
    });
```

Kindly help me in resolving this issue

Regards

**Comment by kaktus40** [comment]
It's an issue for Cesium team. It's not my part. You should submit them this issue (first 28 lines)
