### ISSUE TITLE
Please confirm runtime requirements

### ISSUE THREAD

**Issue by HeavenlyHost** [kaktus40/Cesium-GeoserverTerrainProvider#25]
Hi there,

I have been attempting to get your terrain provider working for geoserver and I would like tyo ask can you confirm that this works with Cesium 1.37 and Geoserver 2.11.2 ?

Regards

**Comment by kaktus40** [comment]
Hello, for now I didn't test with the version you defined. Sorry

**Comment by HeavenlyHost** [comment]
Cesium or Geoserver ?

**Comment by kaktus40** [comment]
Cesium and Geoserver :-)

**Comment by HeavenlyHost** [comment]
ok, can you confirm the maximum version of the Cesium and Geoserver that this has been tested with, cheers.

**Comment by kaktus40** [comment]
Just for information I tested sucessfully with Cesium 1.38 and geoserver 2.11.2
