### ISSUE TITLE
Error url not defined

### ISSUE THREAD

**Issue by ruediger-brand** [kaktus40/Cesium-GeoserverTerrainProvider#27]
Hi,

I hot an error with the latest version - with Cesium 1.33.

In line 1031
var promise = Cesium.loadArrayBuffer(url, Cesium.loadImage);

url is not defined - why does this work at yours ?

Rüdiger

**Comment by kaktus40** [comment]
Damn, I didn't see it!

**Comment by je-an** [comment]
We got the same issue, can you give us a date when this will be fixed? If it will take too long we will have to go back to an old cesium version for our next release :(

Kind regards
Jerry

**Comment by kaktus40** [comment]
I just push a correction

**Comment by je-an** [comment]
hey, 
the terrain works now, but i get the following result:

![terrain](https://user-images.githubusercontent.com/25503105/32039715-f2a3acd6-ba2e-11e7-86bd-c0f26e1de11b.PNG)

If you want, i can provide the 8bit rgb tif which is used

**Comment by kaktus40** [comment]
Hello, you should check a previous comment [here](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/7#issuecomment-85410227) (first point only)
