### ISSUE TITLE
Maximum use accuracy

### ISSUE THREAD

**Issue by xuncanzhe** [kaktus40/Cesium-GeoserverTerrainProvider#29]
Hi， I am loading **5m** resolution DTM on cesium globe. 
![qq 20180720162420](https://user-images.githubusercontent.com/7651130/42992063-16be99c2-8c3a-11e8-801b-a043370943ff.png)
It seems to lose accuracy. And the browser does not seem to request higher resolution image data.
How can I optimize and improve accuracy?

**Comment by kaktus40** [comment]
Hello,
you should set maxLevel above 11. see [here](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/WMSParameters.md)

**Comment by xuncanzhe** [comment]
thanks
