### ISSUE TITLE
如何在geoserver 中发布高程，以及如何在cesium1.55中使用该插件？

### ISSUE THREAD

**Issue by HuZhuangQiang** [kaktus40/Cesium-GeoserverTerrainProvider#30]
如何在geoserver 中发布高程，以及如何在cesium1.55中使用该插件>

**Comment by kaktus40** [comment]
Sorry I don't understand

**Comment by HuZhuangQiang** [comment]
@kaktus40 ,
     var terrainProvider = new Cesium.GeoserverTerrainProvider({   
      url: 'http://localhost:8080/geoserver/sf/wms', //wms服务地址
      layerName: 'sf:sfdem', //图层   
      waterMask:true              
    });
    viewer.terrainProvider = terrainProvider;
Can this be achieved? How to import and publish elevation data in geoserver？

**Comment by kaktus40** [comment]
``
var terrainProvider = new Cesium.GeoserverTerrainProvider({
			url : 'http://localhost:8080/geoserver/ows',
			layerName: 'sf:sfdem', 
			heightMapWidth: 65,
			maxLevel: 12,
			waterMask:false,
			service: "WMS"
		});
viewer.terrainProvider = terrainProvider;
``

Little helps to use SRTM (elevation maps) in geoserver

    you can download SRTM data at [http://srtm.csi.cgiar.org/](http://srtm.csi.cgiar.org/) or [http://www.viewfinderpanoramas.org/](http://www.viewfinderpanoramas.org/) (90 meters or 3 seconds arc resolution of map is better)
    install GDAL tools and python to work with SRTM [http://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries](http://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries)
    install geoserver image pyramid plugin
    generate a pyramid from SRTM data with gdal_retile command from GDAL tools
    create a layer from generated pyramid ( a guide is available [here](http://docs.geoserver.org/latest/en/user/tutorials/imagepyramid/imagepyramid.html))

**Comment by HuZhuangQiang** [comment]
@kaktus40 ，Thank you very much for your help, but the current implementation is as follows:
![捕获](https://user-images.githubusercontent.com/33933148/54664150-61988b80-4b1e-11e9-932b-f6be77ea70e4.JPG)


Is there any good solution?

**Comment by kaktus40** [comment]
Did you check the closed issues? There is a lot talking same problem.
