### ISSUE TITLE
Terrain Gaps and Artifacts Introduced After Conversion

### ISSUE THREAD

**Issue by masonr** [kaktus40/Cesium-GeoserverTerrainProvider#31]
I'm running into an issue where it appears that at tile boundaries, the terrain doesn't quite match up. This leads to gaps, pits, and artifacts being introduced into the converted product. The current area that I'm looking at uses two DTED files that I merge together (after converting to TIF).

I've tested a couple sources of DTED/SRTF (Level 1 & Level 2) DT1/DT2 files and also TanDEM-X GeoTIFFs. All sources I tested have this same issue at the same locations on the earth, so I think this rules out an issue with the source of the data itself. Below are my general steps to using the DTED data within Cesium via GeoServer:

```
# convert DT2 to TIF
gdal_translate {source}.DT2 {out}.tif

# Use GeotiffTranslate to convert to 8-bit RGB TIF
java -jar GeotiffTranslate.jar -i .\path\to\tif -o .\path\to\out 

# Merge TIFs into single file
gdal_merge.py -o {merged}.tif {converted_file_1}.tif {converted_file_2}.tif

# Use the retile utility to prep for use with WMS
gdal_retile.py -v -r cubic -levels 4 -ps 512 512 -co "TILED=YES" -targetDir {output_dir} {input_tifs}

# Add new "ImagePyramid" data store in GeoServer under the "elevation" workspace

# Set terrain provider to GeoServer's new terrain layer using a new Cesium.GeoserverTerrainProvider object
```

When viewing the area that the terrain includes within Cesium, I observe the gaps and artifacts shown in the screenshots below. Most of the area is perfectly fine and doesn't have these issues, but about 25% of the Western side of the area does. Any advice or things to try would be appreciated.

![cesium-terrain-2](https://user-images.githubusercontent.com/8313125/55726694-6b573580-59de-11e9-9b99-c20a3eac93db.png)

![cesium-terrain-3](https://user-images.githubusercontent.com/8313125/55726702-701be980-59de-11e9-9f14-ad4d5b4496e7.png)

**Comment by kaktus40** [comment]
Hello,
first you don't need to merge files to use gdal_retile. It's more interesting to use gdalvrt to generate a virtual file that you use as parameter of gdal_retile. 
Tests with gdalvrt and come back with your result.

**Comment by masonr** [comment]
Tried using gdalvrt and ended up with the same result (screenshot below). I'm wondering if it's the MGRS -> Lat/Lon coordinate system conversion that's causing this. Or how'd I would even go about diagnosing/fixing it if that turned out to be the case.

![cesium-terrain-4](https://user-images.githubusercontent.com/8313125/55816877-4daecc80-5ac1-11e9-9cca-2e988aaa09ee.png)

Here's the exact commands I used:

```
gdal_translate {file_1}.DT2 {file_1}.tif
gdal_translate {file_2}.DT2 {file_2}.tif

java -jar GeotiffTranslate.jar -i {path/to/tifs} -o {path/to/out}

gdalbuildvrt dted.vrt {path/to/out/file_1}.tif {path/to/out/file_2}.tif

gdal-retile.py -v -r cubic -levels 4 -ps 512 512 -co "TILED=YES" -targetDir {tiled-dir} dted.vrt
```

Then I add store in geoserver using the "ImagePyramid" tool and point to the directory containing all the tiled images. Keep all the defaults. Publish layer. Add as terrain provider in Cesium.

**Comment by kaktus40** [comment]
**don't translate** your dted data!
```
gdalbuildvrt dted.vrt {file_1}.DT2 {file_2}.DT2
gdal-retile.py -v -r cubic -levels 4 -ps 512 512 -co "TILED=YES" -targetDir {tiled-dir} dted.vrt

gdal-retile.py -v -r cubic -levels 4 -ps 512 512 -co "TILED=YES" -targetDir {tiled-dir} dted.vrt
```

**Comment by masonr** [comment]
Sorry about that. Just redid it using the method you described. Using the 'grayToColor' geoserver style. Here's the result -

![cesium-terrain-5](https://user-images.githubusercontent.com/8313125/55821328-3543af80-5acb-11e9-995e-cb67e9f610a8.png)

Lots of jagged peaks and gaps in the terrain.

**Comment by kaktus40** [comment]
did you use bil/dds plugin?

**Comment by masonr** [comment]
Negative. Tried using it but my geoserver instance wouldn't start up when the java libraries were added. I'll give that another shot now and report back.

**Comment by masonr** [comment]
Interestingly enough, it looks identical as the first method I tried (in the OP) -

![cesium-terrain-6](https://user-images.githubusercontent.com/8313125/55822567-e21f2c00-5acd-11e9-9a73-fefd379eb3dd.png)

This is using just the gdalbuildvrt and gdal_retile commands. 

These are my BIL settings for the terrain layer I'm using -

![image](https://user-images.githubusercontent.com/8313125/55822678-1e528c80-5ace-11e9-96af-f4a21b7f66ee.png)

**Comment by kaktus40** [comment]
well, did you test with other elevation datas like [srtm](http://www.viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org3.htm)? What is the precision of your data?

**Comment by masonr** [comment]
Welp... I figured out the problem. I wasn't grabbing all of the terrain tiles that I needed for the area that I'm looking at, so the gaps and anomalies were a result of missing terrain data for that area. I'm not really sure why it's not all the same elevation for areas with missing data, so that's why I never thought that this would be the problem in the first place.

I was assuming that a file named for example, "W100/N20.DT2" contained the data for W100°-101°, N20°-21°. In reality, this file contains data for W**99**°-100°, N20°-21°. Complete facepalm moment for me as I wasted many hours trying to debug this and the issue would have been easily spotted had I inspected the files from the start (via gdalinfo).

Everything is working great, now that I have the right data! I really appreciate all of your help @kaktus40 and am truly sorry for wasting your time dealing with my mistake. Your tool has proved extremely valuable for our offline usage. Thanks and sorry again!

**Comment by kaktus40** [comment]
No problem. Goob luck

**Comment by yogimlim** [comment]
I am using CesiumJs version 1.89 with @kaktus40 GeoserverTerrainProvider and my code as given below:

  Cesium.Ion.defaultAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3MjA5Zjk0ZC0yM2U0LTQ2NTgtOGQyNi1lNDRlNDU4YmJmYTIiLCJpZCI6NzYwMDksImlhdCI6MTY0NTc4NjYwOH0.****************";
        var terrainProvider = new Cesium.GeoserverTerrainProvider({
            service: "WMS",
            url: "http://mydomain****/geoserver/JAMMU_KASHMIR/wms",
            layerName: "JAMMU_KASHMIR:DEM",
            // xml: xmlGetCapabilities,
            //  proxy: proxy,
            heightMapWidth: 64,
            heightMapHeight: 64,
            offset: 0,
            highest: 12000,
            lowest: -500,
            styleName: "grayToColor",
            hasStyledImage: true,
            waterMask: true,
            maxLevel: 11,
            formatImage: { format: "image/png", extension: "png" },
            formatArray: {
                format: "image/bil",
                postProcessArray: function (bufferIn, size, highest, lowest, offset) {
                    var resultat;
                    var viewerIn = new DataView(bufferIn);
                    var littleEndianBuffer = new ArrayBuffer(size.height * size.width * 2);
                    var viewerOut = new DataView(littleEndianBuffer);
                    if (littleEndianBuffer.byteLength === bufferIn.byteLength) {
                        // time to switch bytes!!
                        var temp, goodCell = 0, somme = 0;
                        for (var i = 0; i < littleEndianBuffer.byteLength; i += 2) {
                            temp = viewerIn.getInt16(i, false) - offset;
                            if (temp > lowest && temp < highest) {
                                viewerOut.setInt16(i, temp, true);
                                somme += temp;
                                goodCell++;
                            } else {
                                var val = (goodCell == 0 ? 1 : somme / goodCell);
                                viewerOut.setInt16(i, val, true);
                            }
                        }
                        resultat = new Int16Array(littleEndianBuffer);
                    }
                    return resultat;
                }
            }
        });
        var viewer = new Cesium.Viewer("cesiumContainer");
        var scene = viewer.scene;

        var globe = new Cesium.Globe(Cesium.Ellipsoid.WGS84);
        //viewer.scene.globe = globe;

        var ellipsoid = viewer.scene.globe.ellipsoid;
        viewer.terrainProvider = terrainProvider;

![image](https://user-images.githubusercontent.com/103253115/162420146-5241e3f7-d0f2-4353-a2c8-9eb0ecc1224d.png)

after that scene globe being hide.
viewer.terrainProvider = terrainProvider;

 viewer.scene.globe.terrainProvider = terrainProvider;
nothing is working for me...
@kaktus40 or anyone ..... please help.
thanks in advance

**Comment by kaktus40** [comment]
Hello, could you show u=your console log?

**Comment by yogimlim** [comment]
![image](https://user-images.githubusercontent.com/103253115/162662268-faaaaec4-3256-48c9-956e-f7383e4950c6.png)


there is no errors in console log

[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
Cesium.js:90 [Violation] 'requestAnimationFrame' handler took 111ms

**Comment by kaktus40** [comment]
could you send your capabilities document from geoserver?

**Comment by yogimlim** [comment]
Geoserver WMS_Capabilities :


This XML file does not appear to have any style information associated with it. The document tree is shown below.
<WMS_Capabilities xmlns="http://www.opengis.net/wms" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" updateSequence="5229" xsi:schemaLocation="http://www.opengis.net/wms http://www.mlinfomap.net/geoserver/schemas/wms/1.3.0/capabilities_1_3_0.xsd">
<Service>
<Name>WMS</Name>
<Title>GeoServer Web Map Service</Title>
<Abstract>A compliant implementation of WMS plus most of the SLD extension (dynamic styling). Can also generate PDF, SVG, KML, GeoRSS</Abstract>
<KeywordList>
<Keyword>WFS</Keyword>
<Keyword>WMS</Keyword>
<Keyword>GEOSERVER</Keyword>
</KeywordList>
<OnlineResource xlink:type="simple" xlink:href="http://mlinfomap.net/"/>
<ContactInformation>
<ContactPersonPrimary>
<ContactPerson>Aditya Sareen</ContactPerson>
<ContactOrganization>ML INFOMAP PVT LTD</ContactOrganization>
</ContactPersonPrimary>
<ContactPosition>Project Manager</ContactPosition>
<ContactAddress>
<AddressType>Work</AddressType>
<Address/>
<City>New Delhi</City>
<StateOrProvince/>
<PostCode/>
<Country>India</Country>
</ContactAddress>
<ContactVoiceTelephone/>
<ContactFacsimileTelephone/>
<ContactElectronicMailAddress>aditya@mlinfomap.com</ContactElectronicMailAddress>
</ContactInformation>
<Fees>NONE</Fees>
<AccessConstraints>NONE</AccessConstraints>
</Service>
<Capability>
<Request>
<GetCapabilities>
<Format>text/xml</Format>
<DCPType>
<HTTP>
<Get>
<OnlineResource xlink:type="simple" xlink:href="http://www.mlinfomap.net/geoserver/ows?SERVICE=WMS&"/>
</Get>
<Post>
<OnlineResource xlink:type="simple" xlink:href="http://www.mlinfomap.net/geoserver/ows?SERVICE=WMS&"/>
</Post>
</HTTP>
</DCPType>
</GetCapabilities>
<GetMap>
<Format>image/png</Format>
<Format>application/atom+xml</Format>
<Format>application/json;type=utfgrid</Format>
<Format>application/pdf</Format>
<Format>application/rss+xml</Format>
<Format>application/vnd.google-earth.kml+xml</Format>
<Format>application/vnd.google-earth.kml+xml;mode=networklink</Format>
<Format>application/vnd.google-earth.kmz</Format>
<Format>image/geotiff</Format>
<Format>image/geotiff8</Format>
<Format>image/gif</Format>
<Format>image/jpeg</Format>
<Format>image/png; mode=8bit</Format>
<Format>image/svg+xml</Format>
<Format>image/tiff</Format>
<Format>image/tiff8</Format>
<Format>image/vnd.jpeg-png</Format>
<Format>image/vnd.jpeg-png8</Format>
<Format>text/html; subtype=openlayers</Format>
<Format>text/html; subtype=openlayers2</Format>
<Format>text/html; subtype=openlayers3</Format>
<DCPType>
<HTTP>
<Get>
<OnlineResource xlink:type="simple" xlink:href="http://www.mlinfomap.net/geoserver/ows?SERVICE=WMS&"/>
</Get>
</HTTP>
</DCPType>
</GetMap>
<GetFeatureInfo>
<Format>text/plain</Format>
<Format>application/vnd.ogc.gml</Format>
<Format>text/xml</Format>
<Format>application/vnd.ogc.gml/3.1.1</Format>
<Format>text/xml; subtype=gml/3.1.1</Format>
<Format>text/html</Format>
<Format>application/json</Format>
<DCPType>
<HTTP>
<Get>
<OnlineResource xlink:type="simple" xlink:href="http://www.mlinfomap.net/geoserver/ows?SERVICE=WMS&"/>
</Get>
</HTTP>
</DCPType>
</GetFeatureInfo>
</Request>
<Exception>
<Format>XML</Format>
<Format>INIMAGE</Format>
<Format>BLANK</Format>
<Format>JSON</Format>
</Exception>
<Layer>
<Title>GeoServer Web Map Service</Title>
<Abstract>A compliant implementation of WMS plus most of the SLD extension (dynamic styling). Can also generate PDF, SVG, KML, GeoRSS</Abstract>

<CRS>AUTO:42001</CRS>
<CRS>AUTO:42002</CRS>
<CRS>AUTO:42003</CRS>
<CRS>AUTO:42004</CRS>
<CRS>AUTO:97001</CRS>
<CRS>AUTO:97002</CRS>
<CRS>EPSG:4326</CRS>
....
....
<CRS>CRS:84</CRS>
<EX_GeographicBoundingBox>
<westBoundLongitude>76.69298109266497</westBoundLongitude>
<eastBoundLongitude>77.23230712890629</eastBoundLongitude>
<southBoundLatitude>8.30873019748267</southBoundLatitude>
<northBoundLatitude>8.89461003000006</northBoundLatitude>
</EX_GeographicBoundingBox>
<BoundingBox CRS="CRS:84" minx="76.69298109266497" miny="8.30873019748267" maxx="77.23230712890629" maxy="8.89461003000006"/>
<BoundingBox CRS="EPSG:4326" minx="8.30873019748267" miny="76.69298109266497" maxx="8.89461003000006" maxy="77.23230712890629"/>
<Style>
<Name>ForestDss:Forest_DSS_watershed_thiruv</Name>
<Title>watershed</Title>
<LegendURL width="20" height="20">
<Format>image/png</Format>
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://www.mlinfomap.net/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=ForestDss%3Awatershed_thiruv_24_12_2019"/>
</LegendURL>
</Style>
</Layer>
</Layer>
</Capability>
</WMS_Capabilities>
