### ISSUE TITLE
can't get response from geoserver

### ISSUE THREAD

**Issue by yanchenjun00** [kaktus40/Cesium-GeoserverTerrainProvider#32]
In accordance with the above, But can't get response from geoserver; Maybe the url has some problem, Could you show the url ; 

thanks

**Comment by yanchenjun00** [comment]
request url：http://localhost:4000/geoserver/goldwind/wms?SERVICE=WMS&REQUEST=GetCapabilities&tiled=true
response：
<?xml version="1.0" encoding="UTF-8"?><WMS_Capabilities version="1.3.0" updateSequence="333" xmlns="http://www.opengis.net/wms" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wms http://localhost:4000/geoserver/schemas/wms/1.3.0/capabilities_1_3_0.xsd">
  <Service>
    <Name>WMS</Name>
    <Title>GeoServer Web Map Service</Title>
    <Abstract>A compliant implementation of WMS plus most of the SLD extension (dynamic styling). Can also generate PDF, SVG, KML, GeoRSS</Abstract>
    <KeywordList>
      <Keyword>WFS</Keyword>
      <Keyword>WMS</Keyword>
      <Keyword>GEOSERVER</Keyword>
    </KeywordList>
    <OnlineResource xlink:type="simple" xlink:href="http://geoserver.org"/>
    <ContactInformation>
      <ContactPersonPrimary>
        <ContactPerson>Claudius Ptolomaeus</ContactPerson>
        <ContactOrganization>The Ancient Geographers</ContactOrganization>
      </ContactPersonPrimary>
      <ContactPosition>Chief Geographer</ContactPosition>
      <ContactAddress>
        <AddressType>Work</AddressType>
        <Address/>
        <City>Alexandria</City>
        <StateOrProvince/>
        <PostCode/>
        <Country>Egypt</Country>
      </ContactAddress>
      <ContactVoiceTelephone/>
      <ContactFacsimileTelephone/>
      <ContactElectronicMailAddress>claudius.ptolomaeus@gmail.com</ContactElectronicMailAddress>
    </ContactInformation>
    <Fees>NONE</Fees>
    <AccessConstraints>NONE</AccessConstraints>
  </Service>
  <Capability>
    <Request>
      <GetCapabilities>
        <Format>text/xml</Format>
        <DCPType>
          <HTTP>
            <Get>
              <OnlineResource xlink:type="simple" xlink:href="http://localhost:4000/geoserver/goldwind/ows?SERVICE=WMS&amp;"/>
            </Get>
            <Post>
              <OnlineResource xlink:type="simple" xlink:href="http://localhost:4000/geoserver/goldwind/ows?SERVICE=WMS&amp;"/>
            </Post>
          </HTTP>
        </DCPType>
      </GetCapabilities>...
where is My problem?
thanks very mach

**Comment by kaktus40** [comment]
Can you give more context?

**Comment by yanchenjun00** [comment]
surprised,thanks very much!
A little while,I'll sort it out and send it to you.






------------------ 原始邮件 ------------------
发件人: "kaktus40"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 中午12:44
收件人: "kaktus40/Cesium-GeoserverTerrainProvider"<Cesium-GeoserverTerrainProvider@noreply.github.com>;
抄送: "阳光"<976876409@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kaktus40/Cesium-GeoserverTerrainProvider] can't get responsefrom geoserver (#32)




Can you give more context?

**Comment by yanchenjun00** [comment]
------------------ 原始邮件 ------------------
  发件人: "kaktus40"<notifications@github.com>;
 发送时间: 2019年4月23日(星期二) 中午12:44
 收件人: "kaktus40/Cesium-GeoserverTerrainProvider"<Cesium-GeoserverTerrainProvider@noreply.github.com>;
 抄送: "阳光"<976876409@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [kaktus40/Cesium-GeoserverTerrainProvider] can't get responsefrom geoserver (#32)

 

 
Can you give more context?

**Comment by yanchenjun00** [comment]
thanks,I find my problem
