### ISSUE TITLE
what is the xmlGetCapabilities 

### ISSUE THREAD

**Issue by yanchenjun00** [kaktus40/Cesium-GeoserverTerrainProvider#33]

**Comment by kaktus40** [comment]
once again can you explain your issue?

**Comment by yanchenjun00** [comment]
xml: xmlGetCapabilities,

**Comment by yanchenjun00** [comment]
this is a variable，but it is undefined

**Comment by kaktus40** [comment]
I don't understand what you mean by xmlGetCapabilities. There is no variable named xmlGetCapabilities in my code

**Comment by yanchenjun00** [comment]
in WMSParameters.md

**Comment by kaktus40** [comment]
well it's an example where each parameter is explained in the table below.

**Comment by yanchenjun00** [comment]
I do,thanks
