### ISSUE TITLE
geoserver 中使用“图层组”后，地形是阶梯状

### ISSUE THREAD

**Issue by HuZhuangQiang** [kaktus40/Cesium-GeoserverTerrainProvider#34]
使用geoserver 中的“图层组” ，合并图层后，cesium中显示的地形是阶梯状的，请问有什么解决方法吗

**Comment by kaktus40** [comment]
Sorry I don't understand.

**Comment by HuZhuangQiang** [comment]
![捕获](https://user-images.githubusercontent.com/33933148/57761618-749b9680-7730-11e9-8b39-a734da4fa47f.PNG)
使用 图层组（layerGroup）添加的多个图层，在cesium 中是阶梯状的，但是单个图层是对的

**Comment by kaktus40** [comment]
Sorry I don't understand your language!
