### ISSUE TITLE
only half of the world map is rendered/wrapped around cesium globe when loaded the terrain from geoserver

### ISSUE THREAD

**Issue by chaitanyajalluri** [kaktus40/Cesium-GeoserverTerrainProvider#35]
Hi, 
I have loaded the terrain from geoserver using GeoserverTerrainProvider using cesium but after getting loaded only half of the world map is wrapped. Please help me...

**Comment by kaktus40** [comment]
hello I invite you to check the previous closed issues! see [here](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/7)

**Comment by chaitanyajalluri** [comment]
can u help where to modify/edit the method getTileDataAvailable.

**Comment by kaktus40** [comment]
you should review previous issues: [here](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/7) for example or [here](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/19)
