### ISSUE TITLE
blocky terrain question

### ISSUE THREAD

**Issue by mortac8** [kaktus40/Cesium-GeoserverTerrainProvider#38]
Attached is a comparison of cgiar srtm 90m from http://srtm.csi.cgiar.org/download with Cesium World Terrain.  Is there a way to reduce the blockiness of the terrain?  Or is this just a result of using only 90m terrain resolution?  

I configured my GeoserverTerrainProvider.js to use the 'mySLD.xml option' with WMTS.  Thanks for your time! @kaktus40 

![image](https://user-images.githubusercontent.com/1685158/84542156-77afe000-acbe-11ea-9761-0b0eceebdcf7.png)

**Comment by kaktus40** [comment]
Hello

from what I see, it seems you don't use a good configuration of the  bil/dds plugin. Did you try different configurations? What is your process to generate your tiff files?

**Comment by mortac8** [comment]
I am not using the bil/dds plugin.  I just loaded 90m terrain files from http://srtm.csi.cgiar.org/download into an ImageMosaic in GeoServer then I simply configured my layer to use the mySLD.xml style from your Github.

What is the best way?  Is it the bil/dds plugin or maybe the GeotiffTranslate script?

	var terrainProvider = new Cesium.GeoserverTerrainProvider({
		service : "WMTS",
		url : "http://localhost:8080/geoserver/gwc/service/wmts",
        layerName: "cite:srtm90",
        styleName: "mySLD",
        waterMask: true
    });

**Comment by kaktus40** [comment]
You should check the README.md. There is a comparison for each type and some hints for processing your data.

**Comment by mortac8** [comment]
Ok I got it to work for WMS by:

- installing dds plugin from https://docs.geoserver.org/latest/en/user/community/dds/index.html via https://build.geoserver.org/geoserver/2.17.x/community-latest/

- using your example at https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/WMSParameters.md

Thank you!

What is the way to get the best performance?  Use service:"WMS" providing a gwc wms endpoint?

	var terrainProvider = new Cesium.GeoserverTerrainProvider({
		service: "WMS",
		url : "http://localhost:8080/geoserver/cite/wms",
		layerName: "srtm90",
		//service: "WMTS",
		//url : "http://localhost:8080/geoserver/gwc/service/wmts",
		//layerName: "cite:srtm90",
		heightMapWidth: 64,
		heightMapHeight: 64,
		offset: 0,
		highest: 12000,
		lowest: -500,
		styleName: "mySLD",
		hasStyledImage: true,
		waterMask: true,
		maxLevel: 11,
		formatImage: {format : "image/png",extension: "png"},
		formatArray: {
			format : "image/bil",
			postProcessArray : function(bufferIn, size,highest,lowest,offset) {
				var resultat;
				var viewerIn = new DataView(bufferIn);
				var littleEndianBuffer = new ArrayBuffer(size.height * size.width * 2);
				var viewerOut = new DataView(littleEndianBuffer);
				if (littleEndianBuffer.byteLength === bufferIn.byteLength) {
					// time to switch bytes!!
					var temp, goodCell = 0, somme = 0;
					for (var i = 0; i < littleEndianBuffer.byteLength; i += 2) {
						temp = viewerIn.getInt16(i, false)-offset;
						if (temp > lowest && temp < highest) {
							viewerOut.setInt16(i, temp, true);
							somme += temp;
							goodCell++;
						} else {
							var val = (goodCell == 0 ? 1 : somme / goodCell);
							viewerOut.setInt16(i, val, true);
						}
					}
					resultat = new Int16Array(littleEndianBuffer);
				}
				return resultat;
			}
		}
	});

**Comment by kaktus40** [comment]
For a best performance, I should use WMTS (cached tiles!)

Le 12/06/2020 à 23:39, mortac8 a écrit :

**Comment by mortac8** [comment]
Does GeoServer/GeoWebCache WMTS support .bil?  
Whenever I try to use WMTS I get either blocky or spiky terrain using GeoserverTerrainProvider.js as it's just using .png or .jpeg and doesn't seem to go through the more accurate .bil pipeline.

**Comment by kaktus40** [comment]
Unfortunately WMTS doesn't support .bil. So you need to convert your 
tiff with the GeotiffTranslate script. It change elevation data into 
tiff files into colors (Red, Green, Blue information contains the 
elevation data).

With it you can use WMTS and you should use png type and not jpeg which 
is not a lossless format...

Le 13/06/2020 à 00:25, mortac8 a écrit :

**Comment by mortac8** [comment]
I ran the GeotiffTranslate onthe srtm4.1 dataset (90m).  It looks close but the .bil solution seems to have more accurate terrain.  Visually the .bil solution looks better.  Has this been your experience?

**Comment by kaktus40** [comment]
Well done, that is normal. Is it now ok for you?

Le 14/06/2020 à 07:55, mortac8 a écrit :

**Comment by mortac8** [comment]
Do you believe the best solution could be as follows?

```
gdalbuildvrt mosaic.vrt c:\srtm90\*.tif

gdal_retile -ps 2048 2048 -overlap 0 -levels 6 -s_srs EPSG:4326 -r cubicspline -ot Int16 -co TILED=YES -co COMPRESS=DEFLATE -targetDir srtm90pyramid mosaic.vrt
```
The deploy srtm90pyramid as an ImagePyramid in GeoServer and use image/bil method?

**Comment by kaktus40** [comment]
For me it's the optimal solution for the best rendering. Nevertheless, 
you should be aware that Cesium use 2 rendering modes. I use the 
HeightmapTerrainData version and Cesium use QuantizedMeshTerrainData 
that is smoother in high zoom. You should see the other issues for that!

Le 14/06/2020 à 08:12, mortac8 a écrit :

**Comment by mortac8** [comment]
I'm good with closing this Issue.  Thanks for your advice!
