### ISSUE TITLE
Using latest version of cesium

### ISSUE THREAD

**Issue by NyakudyaA** [kaktus40/Cesium-GeoserverTerrainProvider#39]
What is the status of using this with the latest version of cesium? And what is the minimum version we need to use to get this running with GeoServer terrain

**Comment by kaktus40** [comment]
Hello, I dont always test the latest version but the API of Cesium didn't change about what I'm using in this repo. Also it should work.

**Comment by meomancer** [comment]
hi @kaktus40 
thank you for reply
i'm using cesium latest cesium 1.71
> <script src="https://cesium.com/downloads/cesiumjs/releases/1.71/Build/Cesium/Cesium.js"></script>

when using the example on readme, i got this error
```
Cesium.js:1 Uncaught TypeError: Cannot read property 'getContext' of undefined
    at new Context (Cesium.js:1)
    at new Scene (Cesium.js:1)
    at index.html:10
```
it is from 
```
var scene = new Cesium.Scene(canvas);
```

thank you

**Comment by kaktus40** [comment]
Hello,
I just update the plugin to be compliant with cesium 1.72

**Comment by PatrickMugayaJoel** [comment]
Hi @kaktus40
My provided map does not display in cesium and I can't figure out why.
Kindly take a look at these files and see if anything stands out.

[geoserver capabilities file](https://drive.google.com/file/d/1PFY8CqPkqChhnUsDsqcWlBvYk-ENEZ8_/view?usp=sharing)
[HTML file1](https://drive.google.com/file/d/1CbdZxQsCNu3cKyg6jcHOvG67kDykKx4w/view?usp=sharing)
[HTML file2](https://drive.google.com/file/d/14iej4iGBWrc4IbczPSDPUE8CVldiXAHO/view?usp=sharing)

HTML file1 only displays a black rectangular box.
HTML file2 displays a the blue globe.

Any assistance is much appreciated

**Comment by NyakudyaA** [comment]
> Hi @kaktus40
> My provided map does not display in cesium and I can't figure out why.
> Kindly take a look at these files and see if anything stands out.
> 
> [geoserver capabilities file](https://drive.google.com/file/d/1PFY8CqPkqChhnUsDsqcWlBvYk-ENEZ8_/view?usp=sharing)
> [HTML file1](https://drive.google.com/file/d/1CbdZxQsCNu3cKyg6jcHOvG67kDykKx4w/view?usp=sharing)
> [HTML file2](https://drive.google.com/file/d/14iej4iGBWrc4IbczPSDPUE8CVldiXAHO/view?usp=sharing)
> 
> HTML file1 only displays a black rectangular box.
> HTML file2 displays a the blue globe.
> 
> Any assistance is much appreciated

hi @PatrickMugayaJoel I wrote a blog article https://kartoza.com/en/blog/publishing-digital-elevation-in-cesium/ about this. Maybe you could take a look at what I did there
