### ISSUE TITLE
conditions when zooming in on the terrain

### ISSUE THREAD

**Issue by farhanbadrussalam** [kaktus40/Cesium-GeoserverTerrainProvider#40]
hello kaktus40, 

I'm having trouble zooming in on the terrain using the geoserver

when the far zoom looks good, see the image below
![UCScreenshot20200807110236](https://user-images.githubusercontent.com/43528091/89608025-237c4300-d89e-11ea-8dde-c2a40efd0dec.png)

but when zooming in closer it looks like this
![UCScreenshot20200807110254](https://user-images.githubusercontent.com/43528091/89608097-58889580-d89e-11ea-9a37-c3fb3289ffb9.png)
![UCScreenshot20200807110326](https://user-images.githubusercontent.com/43528091/89608160-8bcb2480-d89e-11ea-9483-2c098e8ed520.png)

do you have any suggestions to solve this problem?

Thank you

**Comment by kaktus40** [comment]
Do your elevation cover this region? It seems that you have a poor granularity of data here

**Comment by farhanbadrussalam** [comment]
I want to make the depth of the ocean using a geoserver

**Comment by kaktus40** [comment]
I am not sure that cesium works with depth of the ocean

**Comment by NyakudyaA** [comment]
@farhanbadrussalam I am trying to use the terrain provider but haven't been successful using the latest version. Do you mind letting me know which version of cesium you are using and if you do not mind sharing a working example of using this. We tried to use the example given on the README but to no avail

**Comment by farhanbadrussalam** [comment]
@kaktus40 I'm fixing the geoserver data. If it's still like that when zooming, I'll let you know.
Thank you very much

**Comment by farhanbadrussalam** [comment]
@NyakudyaA I am using cesium version 1.6, yes it can't be used for the latest version, I use the example in Readme which is not much different, it's just that the geoserver data is still not correct

**Comment by farhanbadrussalam** [comment]
@kaktus40 Would you mind giving a correct sample geoserver data?
thank you so much for your help

**Comment by kaktus40** [comment]
Hello,
I just update the plugin to be compliant with cesium 1.72
