### ISSUE TITLE
Using with BIL DTM format ?

### ISSUE THREAD

**Issue by gribouille139** [kaktus40/Cesium-GeoserverTerrainProvider#42]
Hello, I'm trying to use this repo to render DTP flux diffused as BIL images by the provider "IGN" in France.
I posted this issue on CesiumJS repo : https://github.com/CesiumGS/cesium/issues/9426#issue-830043168
```
Hye, 
In France, a public service called Geoportail use WMS flux provided by IGN. Requests are in this format : 
`https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?LAYER=ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES&FORMAT=image/x-bil;bits=32&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=WGS84G&TILEMATRIX=12&TILEROW=1012&TILECOL=4228`
I would like to use this flux as as CesiumTerrainProvider in CesiumJS. 

I tried with https://github.com/kaktus40/Cesium-GeoserverTerrainProvider with no result... 

Any idea please ...?
```
![image](https://user-images.githubusercontent.com/73525724/110936537-55242380-8331-11eb-9ab9-16a967349ac5.png)

Do you have any idea ?

**Comment by kaktus40** [comment]
Bonjour Gribouille139,

Il y a des solutions, tout dépend de tes compétences techniques:

- télécharger le jeux de données de l'[IGN](https://geoservices.ign.fr/documentation/diffusion/telechargement-donnees-libres.html) et l'intégrer dans geoserver comme je le propose avec le plugin;
- monter un serveur proxy qui convertis les données du serveur IGN vers un type de données compatible avec cesium (emploi éventuel de geoserver dans ce cadre et on peut revenir au cas classique).
- création d'un plugin en javascript interprétant directement le type de données BIL pour l'injecter dans cesium.
- adapter mon plugin pour interpréter les données de l'IGN (il faut donc bien s'assurer que c'est du BIL)...

voilà voilà
