### ISSUE TITLE
Stepped Terrain on Low Elevation Zooming

### ISSUE THREAD

**Issue by vistacon21** [kaktus40/Cesium-GeoserverTerrainProvider#45]
Hi, I'm using your library with the following dataset and config geoserver config

**Geoserver plugins**: BIL/DDS, image pyramid

**Source Data**: dted level 2

**Dted2 Conversion Steps**:
- gdalbuildvrt dted2.vrt ./*/*.dt2
- gdal_retile.py -v -r cubic -levels 4 -ps 512 512 -co "TILED=YES" -targetDir dted2-tiles dted2.vrt

**Elevation data store**: Image Pyramid

**BIL Format Settings**
- Application Encoding: application/bil16
- Byte Order: Big Endian

The terrain renders, but on close-in zoom levels, the terrain appears to have a "stepped" appearance. Do you know if there's anything I can do in the conversion process or otherwise to generate the terrain so it doesn't have the stepped appearance on lower elevation zooming?

![stepped-terrain](https://user-images.githubusercontent.com/87329566/128551073-ead4dd0b-4661-4975-838d-00e02380cf68.PNG)

**Comment by kaktus40** [comment]
Hello did you test with dted 3. dted 2 has a precision of 30 meters so could you test with a more precise dataset?
