### ISSUE TITLE
Stepped relief. Please help me understand my error

### ISSUE THREAD

**Issue by bav55** [kaktus40/Cesium-GeoserverTerrainProvider#47]
Hello, @kaktus40! Thanks for the great plugin! 
With difficulty, but I was able to visualize 3d terrain with Your plugin. But I'm not happy with the result.
My result:
![image](https://user-images.githubusercontent.com/2253306/161420379-f92a04d3-a0a6-4199-808e-37727089f6be.png)
And Cesium Terrain Result:
![image](https://user-images.githubusercontent.com/2253306/161420403-dbdf4298-506d-41c6-a568-2ad299fc98fc.png)

In QGIS my WMS Layer looks like that (with SRTM2Color style):
![image](https://user-images.githubusercontent.com/2253306/161420492-0cc11db5-c9e2-4873-b0c0-6a12e274e726.png)

Why do you think the height is displayed incorrectly - stepped?
I will be grateful for any help.

**Comment by bav55** [comment]
`
<script src="https://cesium.com/downloads/cesiumjs/releases/1.91/Build/Cesium/Cesium.js"></script>
<link href="https://cesium.com/downloads/cesiumjs/releases/1.91/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
<script src="js/GeoserverTerrainProvider.js" type="text/javascript"></script>
<script>
    // Your access token can be found at: https://cesium.com/ion/tokens.
    // Replace `your_access_token` with your Cesium ion access token.

    Cesium.Ion.defaultAccessToken = '***Token***';
    var GeoserverterrainProvider = new Cesium.GeoserverTerrainProvider({
	service: "WMS",
	heightMapWidth: 64,
	HeightMapHeight: 64,
	offset: 0,
	highest: 7000,
	lowest: 0,
	hasStyledImage: true,
	formatImage: {format: "image/png", extension: "png"},
        url : "http://maps.int-sys.net:88/geoserver/osm/wms",
        layerName: "srtm-90",
        styleName:"SRTM2Color",
        waterMask:true
    });
    const viewer = new Cesium.Viewer("cesiumContainer", {

	terrainProvider:  GeoserverterrainProvider
    });
    viewer.camera.flyTo({
      destination : Cesium.Cartesian3.fromDegrees(85, 51, 1000),
      orientation : {
        heading : Cesium.Math.toRadians(0.0),
        pitch : Cesium.Math.toRadians(-15.0),
      }
    });
  </script>`

**Comment by kaktus40** [comment]
Hello, I invite you to check closed issues like [this](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/issues/7)

**Comment by bav55** [comment]
Thanks! I'm already watching

**Comment by bav55** [comment]
Thanks! Install bil-dds plugin and reset style for layer (from SRTM2Color to raster) solved my task! Thank again!
