### ISSUE TITLE
issue in showing large dsm files showing spikes and cuts

### ISSUE THREAD

**Issue by bikash153** [kaktus40/Cesium-GeoserverTerrainProvider#53]
![image](https://user-images.githubusercontent.com/28836200/227432355-05b749c7-72db-4e14-9f28-8aca9b200d43.png)

**Comment by bikash153** [comment]
For small images its working fine

**Comment by kaktus40** [comment]
Hi, can you give more context? (see others isuues to see wht I mean)

**Comment by bikash153** [comment]
I am using geoserverterrain provoider bil/dss extension with geoserver 2.21.0 using
bigendian and application/16 bit its working fine for small dsm file

![dsm1](https://user-images.githubusercontent.com/28836200/227448554-8d4bdcbd-5b36-404b-abed-3197e6262457.png)

**Comment by bikash153** [comment]
It works for small file

**Comment by bikash153** [comment]
https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/dist/GeoserverTerrainProvider.js

I am using this file

**Comment by bikash153** [comment]
Is there any solutions

**Comment by kaktus40** [comment]
Can you describe your process to convert your elevation files so I can test from my computer?  
- origin of files
- scripts to transform your files 
- ...

**Comment by bikash153** [comment]
1. DEM DSM and ORTHO are generated from LiDAR based data.
2.It is unsigned 32 bit data
3.We have used gdal to convert it into COG file with deflate compression
4. The generation of DSM and dem were done using Pix4D
5.Tiles were mosaic and severed using geoserver
I am using this script file
https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/dist/GeoserverTerrainProvider.js

 Just let us know how you are doing if you are having the dataset

**Comment by rrorsac** [comment]
!gdal_translate "E:\\bmc\\mk.tif" "E:\\bmc\\bmc_mk_cog.tif" -co BIGTIFF=YES -co TILED=YES -of COG -co COMPRESS=DEFLATE

!gdal_translate "\\ip\Share5\bmc_dsm_mosaic_new.tif" "\\Share5\cog\bmc_dsm_mosaic_cog.tif" -co BIGTIFF=YES -of COG -co COMPRESS=LZW 
we are using this to convert it to cog.

**Comment by bikash153** [comment]
Above are the command for cog conversation
Please let me know

**Comment by kaktus40** [comment]
Well I never worked with Cloud Optimized GeoTIFF. can you send me the capabilities document of your geoserver?

**Comment by bikash153** [comment]
<Layer queryable="1" opaque="0">
<Name>raster:dsm_cog</Name>
<Title>dsm_cog</Title>
<Abstract>Layer-Group type layer: raster:dsm_cog</Abstract>
<KeywordList>
<Keyword>dsm_cog</Keyword>
</KeywordList>
<CRS>EPSG:4326</CRS>
<CRS>CRS:84</CRS>
<EX_GeographicBoundingBox>
<westBoundLongitude>85.72587838395638</westBoundLongitude>
<eastBoundLongitude>85.9094574953808</eastBoundLongitude>
<southBoundLatitude>20.20515349768633</southBoundLatitude>
<northBoundLatitude>20.37644703892337</northBoundLatitude>
</EX_GeographicBoundingBox>
<BoundingBox CRS="CRS:84" minx="85.72587838395638" miny="20.20515349768633" maxx="85.9094574953808" maxy="20.37644703892337"/>
<BoundingBox CRS="EPSG:4326" minx="20.20515349768633" miny="85.72587838395638" maxx="20.37644703892337" maxy="85.9094574953808"/>
<Style>
<Name>raster</Name>
<Title>Opaque Raster</Title>
<Abstract>A sample style that draws a raster, good for displaying imagery</Abstract>
<LegendURL width="20" height="20">
<Format>image/png</Format>
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://maps.in/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=raster%3Adsm_cog"/>
</LegendURL>
</Style>
</Layer>

**Comment by bikash153** [comment]
<Layer queryable="1" opaque="0">
<Name>raster:dsm_cog</Name>
<Title>dsm_cog</Title>
<Abstract>Layer-Group type layer: raster:dsm_cog</Abstract>
<KeywordList>
<Keyword>dsm_cog</Keyword>
</KeywordList>
<CRS>EPSG:4326</CRS>
<CRS>CRS:84</CRS>
<EX_GeographicBoundingBox>
<westBoundLongitude>85.72587838395638</westBoundLongitude>
<eastBoundLongitude>85.9094574953808</eastBoundLongitude>
<southBoundLatitude>20.20515349768633</southBoundLatitude>
<northBoundLatitude>20.37644703892337</northBoundLatitude>
</EX_GeographicBoundingBox>
<BoundingBox CRS="CRS:84" minx="85.72587838395638" miny="20.20515349768633" maxx="85.9094574953808" maxy="20.37644703892337"/>
<BoundingBox CRS="EPSG:4326" minx="20.20515349768633" miny="85.72587838395638" maxx="20.37644703892337" maxy="85.9094574953808"/>
<Style>
<Name>raster</Name>
<Title>Opaque Raster</Title>
<Abstract>A sample style that draws a raster, good for displaying imagery</Abstract>
<LegendURL width="20" height="20">
<Format>image/png</Format>
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://maps.in/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=raster%3Adsm_cog"/>
</LegendURL>
</Style>
</Layer>

**Comment by bikash153** [comment]
<Layer queryable="1" opaque="0">
<Name>raster:dsm_cog</Name>
<Title>dsm_cog</Title>
<Abstract>Layer-Group type layer: raster:dsm_cog</Abstract>
<KeywordList>
<Keyword>dsm_cog</Keyword>
</KeywordList>
<CRS>EPSG:4326</CRS>
<CRS>CRS:84</CRS>
<EX_GeographicBoundingBox>
<westBoundLongitude>85.72587838395638</westBoundLongitude>
<eastBoundLongitude>85.9094574953808</eastBoundLongitude>
<southBoundLatitude>20.20515349768633</southBoundLatitude>
<northBoundLatitude>20.37644703892337</northBoundLatitude>
</EX_GeographicBoundingBox>
<BoundingBox CRS="CRS:84" minx="85.72587838395638" miny="20.20515349768633" maxx="85.9094574953808" maxy="20.37644703892337"/>
<BoundingBox CRS="EPSG:4326" minx="20.20515349768633" miny="85.72587838395638" maxx="20.37644703892337" maxy="85.9094574953808"/>
<Style>
<Name>raster</Name>
<Title>Opaque Raster</Title>
<Abstract>A sample style that draws a raster, good for displaying imagery</Abstract>
<LegendURL width="20" height="20">
<Format>image/png</Format>
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://maps.in/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=raster%3Adsm_cog"/>
</LegendURL>
</Style>
</Layer>

**Comment by kaktus40** [comment]
Is it possible to have the full document?

**Comment by bikash153** [comment]
[wmscapabilities.txt](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/files/11071403/wmscapabilities.txt)

Please find the capability document

**Comment by kaktus40** [comment]
From your file I see that you didn't use bil/dds plugin

**Comment by bikash153** [comment]
Thank You. Resolved the issues.
