### ISSUE TITLE
import?

### ISSUE THREAD

**Issue by alienatorZ** [kaktus40/Cesium-GeoserverTerrainProvider#54]
How would I use this with standard vite project?
I tried import `import {GeoserverTerrainProvider} from "./geoserverterrain/GeoserverTerrainProvider";`
but I get the error:

Uncaught SyntaxError: The requested module '/src/components/Globe/geoserverterrain/GeoserverTerrainProvider.js' does not provide an export named 'GeoserverTerrainProvider' (at GlobeComponent.jsx:9:9)

**Comment by kaktus40** [comment]
Hi,
did you test `import  "./geoserverterrain/GeoserverTerrainProvider";` ? after importing cesium?
After cesium should provide GeoserverTerrainProvider like `cesium.GeoserverTerrainProvider`
