### ISSUE TITLE
Not compatible to Cesium 1.105

### ISSUE THREAD

**Issue by Jean-Dum** [kaktus40/Cesium-GeoserverTerrainProvider#55]
I am currently trying to use geoserverTerrainProvider with Cesium version 1.105.0.
I am aware that geoserverTerrainProvider has been only tested for Cesium 1.95, but I still wanted to try it.

It appears that I have the error "cannot add property GeoserverTerrainProvider, object is not extensible (at index.ts:86)."
Maybe would you know how to bypass this error?

Thank you!

**Comment by Jean-Dum** [comment]
And it seems that typing is also a bit wrong, it may be due to last cesium version

**Comment by kaktus40** [comment]
Hi,
I just updated Cesium to version 1.105.2 and tested but I couldn't reproduce your issue.
Could you please tell me more about your configuration of geoserver layers (capabilities XML document)?

**Comment by Jean-Dum** [comment]
Finally it appears to be minor typescript issues, I removed the `index.ts:86` line and directly imported `GeoserverTerrainProvider `to my file.
Then, it appears that the URLtemplateImage and URLtemplateArray comes from a bad `layerName` input, I corrected it and added an error throwing in case of layerName not found in layerNodes list.

Now it is perfectly working!

**Comment by kaktus40** [comment]
good!
