### ISSUE TITLE
Missing method - loadTileDataAvailability

### ISSUE THREAD

**Issue by lion054** [kaktus40/Cesium-GeoserverTerrainProvider#60]
`Readme.md` says this provider was tested with `cesium v1.95`.
But `GeoserverTerrainProvider` conflicts with `cesium` since `1.70.0`.
Because `loadTileDataAvailability()` was missed.
I hope this issue would be fixed.

**Comment by kaktus40** [comment]
Hi, I don't understand your issue: you talk about cesium v1.70 and the plug in was tested for version v1.95 that is more recent.
I checked the [documentation of cesium](https://cesium.com/learn/cesiumjs/ref-doc/TerrainProvider.html#loadTileDataAvailability) that indicates` loadTileDataAvailability() ` is not mandatory

**Comment by lion054** [comment]
Today retried compilation and faced the different context than yesterday's one.
`GeoserverTerrainProvider` is based on [`CustomHeightmapTerrainProvider`](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/aae4184cd756ee2e188ef33007d254caa2455937/src/plugin/index.ts#L68).
BTW `CustomHeightmapTerrainProvider` was introduced since [`v1.100.0`](https://github.com/CesiumGS/cesium/blob/1.100/packages/engine/Source/Core/CustomHeightmapTerrainProvider.js).

**Comment by kaktus40** [comment]
Yes and so?

**Comment by lion054** [comment]
I don't know how you could test `GeoserverTerrainProvider` with `cesium v1.95` successfully.
Can you please write the correct versions of `cesium` and `@types/cesium` that were used in test?

**Comment by kaktus40** [comment]
from [package.json](https://github.com/kaktus40/Cesium-GeoserverTerrainProvider/blob/master/package.json#L32), I used cesium v1.105.2

**Comment by lion054** [comment]
Just tried `v1.105.2` but still getting error of `loadTileDataAvailability()`.
![image](https://github.com/user-attachments/assets/6b6beacd-7ca3-444f-a3f3-246de1609db7)

**Comment by lion054** [comment]
Your test project doesn't look like typescript, because you are new to this error.

**Comment by lion054** [comment]
`TerrainProvider` defines [`availability`](https://github.com/CesiumGS/cesium/blob/a1b0da48e14ef76abfabfaf4a8a2d6ff26b17559/packages/engine/Source/Core/TerrainProvider.js#L109-L111), but [`CustomHeightmapTerrainProvider`](https://github.com/CesiumGS/cesium/blob/1.105/packages/engine/Source/Core/CustomHeightmapTerrainProvider.js) doesn't cover `availability`.

**Comment by lion054** [comment]
I found out some fixes.
May I open PR?

**Comment by kaktus40** [comment]
I' ll regenerate the dist later
