### ISSUE TITLE
OutOfMemory Error- GeotiffTranslate

### ISSUE THREAD

**Issue by Akimh** [kaktus40/Cesium-GeoserverTerrainProvider#8]
Hello,
I tried to use your GeotiffTranslate app, but I got an OutOfMemoryError (java heap space). I encreased the heap space to 2048 MB but I got the same error. My Ifsar-DEM (.tif format, 16 bit int, grey band) has a size of 350 Mb.  
Java version 8 (32 bit) on a win 7 64 bit machine. 
See screenshot.
![oomerror](https://cloud.githubusercontent.com/assets/12158315/7377552/9193675c-ed93-11e4-98b7-07becbccdbf6.JPG).
Thank you.

**Comment by kaktus40** [comment]
Hello,
You have a very very big image. If you have installed gdal, could you 
send me the return of this command:
gdalinfo /yourDEM//./
I fear you'll have to cut your image and make a folder with more 
manageable images.

For your information a pixel needs 4*8 bits=32 bits to be stored in 
memory. If the resolution of your image is 3000 X 3000 ,you'll need at 
least 3000*3000 *32=275 Mo. For the good work of java, it's around 300 
Mo. Also GeotiffTranslate works on two images, the first is the old 
image and the second the new so finally you'll need 600 Mo of memory to 
work with an image of 3000 X 3000 pixels...

**Comment by Akimh** [comment]
Hello,
thank you for your quick reply. 
Screenshot of the result of the gdalinfo:

![gdalinfo_dem](https://cloud.githubusercontent.com/assets/12158315/7398394/329ee3de-ee5b-11e4-8045-9830864acd19.JPG)

**Comment by kaktus40** [comment]
It's really a big size => you must cut the size of your original tif!!

**Comment by Akimh** [comment]
Thank you for your support and I have another question.
When I try to load the elevation data into a Cesium scene, I got a black view. 
![black view](https://cloud.githubusercontent.com/assets/12158315/7436902/904ab0ae-effe-11e4-955e-6664a079c300.JPG)

My Code :

var ol3d = new olcs.OLCesium({map: map});
var scene = ol3d.getCesiumScene();

        var terrainProvider = new Cesium.GeoserverTerrainProvider({            
        url : "http://localhost:8080/geoserver/Denali/wms",
        layerName: 'Denali:Denali_IfsarDEM_Cut',
            styleName:"raster",            
            waterMask: false        
    });        
    scene.terrainProvider = terrainProvider;
    ol3d.setEnabled(false);

**Comment by kaktus40** [comment]
Sorry, I can't help you about open-layer Cesium library. Did you test 
your terrain in a classical Cesium?

**Comment by Akimh** [comment]
I will give it a try. Thank you.
